### ISSUE TITLE
By default can't open external e.g. gitg for visualize all branches

### ISSUE THREAD

**Issue by gelldur** [flathub/com.github.git_cola.git-cola#13]
Probably issue is with some permissions but already set to allow access for whole filesystem.

```
Traceback (most recent call last):

  File "/app/lib/python3.9/site-packages/cola/cmds.py", line 2911, in launch_history_browser
    core.fork(argv)

  File "/app/lib/python3.9/site-packages/cola/decorators.py", line 24, in _caller
    return caller(f, *args, **opts)

  File "/app/lib/python3.9/site-packages/cola/decorators.py", line 83, in interruptable
    raise e

  File "/app/lib/python3.9/site-packages/cola/decorators.py", line 79, in interruptable
    result = func(*args, **opts)

  File "/app/lib/python3.9/site-packages/cola/core.py", line 289, in _fork_posix
    return subprocess.Popen(encoded_args, cwd=cwd, shell=shell).pid

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: b'/usr/bin/gitg'
```

![image](https://user-images.githubusercontent.com/175790/185883697-d9af9aa7-da71-40d0-acce-58799516afbd.png)

**Comment by Mailaender** [comment]
Sorry, this is one of the major downsides of containerized applications. They can only talk to anything inside the container.

**Comment by gelldur** [comment]
What about modified changes? When I'm using from AUR repository git cola everything seems to be fine.

**Comment by Mailaender** [comment]
Make a new ticket. I don't understand what you mean actually.
